name: dotnet-desktop
on:
  push:
    branches:
      - "release/*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore --configfile NuGet.Config
    - name: Build
      run: dotnet publish -r linux-x64 -c Release
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release_Linux_x64.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release_Linux_x64.zip"
        token: ${{ secrets.GITHUB_TOKEN }}  
    - name: Clean
      run: dotnet clean --configuration Release
    - name: Build-Win
      run: dotnet publish -r linux-x64 -c Release
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release-Win_x64.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release_Win_x64.zip"
        token: ${{ secrets.GITHUB_TOKEN }}  
